# 3 profiles (n+2)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# display
# CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_IDLE_TIMEOUT=6000000
# CONFIG_BT_BAS=n
 CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

CONFIG_ZMK_SLEEP=n

CONFIG_XIAORD_BG_1=y