# This file generates the GitHub Actions matrix
---
include:
  # totem
  - board: nice_nano//zmk
    shield: xiaord sample_split_dongle
    artifact-name: home_sample_split_dongle_xiaord
  #   #cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   #snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: settings_reset
