# This file generates the GitHub Actions matrix
---
include:
  # totem
  - board: nice_nano//zmk
    shield: xiaord totem_central_dongle
    artifact-name: home_totem_central_dongle
  #   #cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   #snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: settings_reset
