name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Trỏ vào file cục bộ trong repo của bạn
    uses: ./.github/workflows/build-hex.yml
    with:
      # Bạn vẫn có thể truyền các tham số như bình thường
      archive_name: "my-custom-firmware"